### ISSUE TITLE
Rank of ndarray

### ISSUE THREAD

**Issue by nannau** [ramonhagenaars/nptyping#10]
Hi - I'm wondering if there's any way to define the explicit rank of an numpy.ndarray in the `Array` class. Does something like `Array[type, rank, shape]` make sense? Or is there an alternative way of achieving this? It would be quite handy.

i.e:
```python3
import numpy as np
from nptyping import Array

arr_1d = np.ones(5) # ndim = 1
arr_2d = np.ones((1,2)) # ndim = 2
arr_3d = np.ones((1,2,3)) # ndim = 3

isinstance(arr_1d, Array[int, 1, 5])     # True
isinstance(arr_2d, Array[int, 2, 1, 2])   # True
isinstance(arr_3d, Array[int, 3, 1, 2, 3])  # True
isinstance(arr_3d, Array[int, 3, 1, 2, 1])  # False
isinstance(arr_3d, Array[int, 2, 1, 2, 3])  # False
```

**Comment by ramonhagenaars** [comment]
Hi nannau.

As there were multiple similar suggestions, I have created a new issue that aims to address them. Please have a look at #12.

**Comment by nannau** [comment]
This has been added in  `1.0.1`.
