### ISSUE TITLE
Variables in shape

### ISSUE THREAD

**Issue by Aerilius** [ramonhagenaars/nptyping#11]
It would be super useful if we could define shapes with (integer) variables. This would allow to **document** which dimensions a method's arguments must have to be compatible. 

Use cases:

- Image manipulation where array shapes represent height, width, number of channels. If I only care about the number of channels, I'd like to specify for example:
    ```
    Array[int, Y, X, 3]
    ```
  If I wanted to add another channel, it would need the same Y and X, no matter what exact integer value Y and X have.

- Matrix multiplication:
    ```
    def matrix_multiplication(
        matrix1: Array[float, L, M]
        matrix2: Array[float, M, N]
    ) -> Array[float, L, N]
    ```

Currently we probably would have to unspecify (`Array[int]`) dimensions or overspecify them (e.g. `Array[int, 100, 150, 3]`).

I don't know whether the shape variables would actually be created as `X = TypeVar("X")` (or if this is only for types, not integers) and how it could also integrate with **type checkers**.

**Comment by ramonhagenaars** [comment]
Hi Aerilius,

As there were multiple similar suggestions, I have created a new issue that aims to address them. Please have a look at #12.
