### ISSUE TITLE
Support for pyright

### ISSUE THREAD

**Issue by bfelbo** [ramonhagenaars/nptyping#16]
nptyping doesn't work with [pyright](https://github.com/microsoft/pyright). It would be amazing if it worked even w/o support for specifying dimensions.

**Comment by ramonhagenaars** [comment]
It looks interesting. I would need to investigate it some more thoroughly to see if we could make it fit.

**Comment by ramonhagenaars** [comment]
Another issue has been opened for this. Please refer to #34.
