### ISSUE TITLE
NDArray fails with Optional NDArray

### ISSUE THREAD

**Issue by SteveDoyle2** [ramonhagenaars/nptyping#17]
I'm trying to make the new NDArray class work with optional inputs.  Any idea what I'm doing wrong?

    from typing import Any, Dict, Union, Optional
    from nptyping import NDArray

    NDArray3float = NDArray[(3, ), float]

    def test_func1(self, x: Optional[NDArray3float]) -> int:
        return 1

    def test_func2(self, x: Optional[Dict[int, NDArray3float]]) -> int:
        return 1

    def test_func3(self, x: Union[None, Dict[int, NDArray3float]]) -> int:
        return 1

**Comment by SteveDoyle2** [comment]
Traceback (most recent call last):
      File ".\typing_test.py", line 5, in <module>
        Optional[NDArray3float]
      File "C:\Python37\lib\typing.py", line 254, in inner
        return func(*args, **kwds)
      File "C:\Python37\lib\typing.py", line 358, in __getitem__
        return Union[arg, type(None)]
      File "C:\Python37\lib\typing.py", line 254, in inner
        return func(*args, **kwds)
      File "C:\Python37\lib\typing.py", line 352, in __getitem__
        parameters = _remove_dups_flatten(parameters)
      File "C:\Python37\lib\typing.py", line 226, in _remove_dups_flatten
        all_params = set(params)
    TypeError: unhashable type: '_NDArrayMeta'

**Comment by ramonhagenaars** [comment]
``_NDArrayMeta`` does not have a ``__hash__`` method, making it impossible to put an ``NDArray`` in an ``Optional`` (or any data type that requires hashing).

I've fixed this in [v1.0.1](https://github.com/ramonhagenaars/nptyping/releases/tag/v1.0.1). Your code will work with this patch.

**Comment by SteveDoyle2** [comment]
Thanks!  That was quick!

It's working perfectly now.
