### ISSUE TITLE
Caching instantiations? (e.g. make `NDArray[int] is NDArray[int]` work?)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ramonhagenaars/nptyping#29]
When using `nptyping` (c813f6d2), I observe the following:
```
>>> from nptyping import NDArray
>>> NDArray is NDArray
True
>>> NDArray[int] is NDArray[int]
False
```

Some possible approaches to remedy:

- (Naive) Memoize based on `item` in `typish.SubscriptableType.__getitem__`. However, that means `NDArray[int] is NDArray[Int[64]]` will not work.
- Memoize based on the simplified args computed. May require some reshuffling; from what it looks like, the current flow is `SubscriptableType` creates the class with `(__args__, __origin__)`, then `_NDarray._after_subscription` sets `(_shape, _type)` based on the method dispatch.

**Comment by EricCousineau-TRI** [comment]
While not directly related, here's some naive "generic" code and using "canonicalized" parameters from our code base:
https://github.com/RobotLocomotion/drake/blob/99ef3fe6147a259a429868e7e0346e5a185a5057/bindings/pydrake/common/cpp_template.py#L152

**Comment by EricCousineau-TRI** [comment]
FTR The following works for me (Python 3.6.9):
```
>>> from typing import List
>>> List[int]
typing.List[int]
>>> List[int] is List[int]
```

**Comment by EricCousineau-TRI** [comment]
Thinking about, one approach:
- Rewrite `_NDArray._after_subscription` and the related construction methods to just resolve to `(size, type)` and return it.
- Define `_NDArrayMeta.__getitem__`, and use this resolve method to get the final args, and then use that for memoization; if none happens, just pass those args to `super().__getitem__`, store the results, and return 'em.

**Comment by EricCousineau-TRI** [comment]
Wrote an example of this here:
https://github.com/EricCousineau-TRI/repro/blob/4a5c71162bf2e3c0afc4d08c5d757aa0841000c4/python/nptyping_ish/test/typing_test.py

Found that for this contract to be easily upheld, I had to enforce the concept of "binding". It feels dirty and confusing, but not sure if it's better or worse than issue pointed out in #31.

**Comment by ramonhagenaars** [comment]
Thank you @EricCousineau-TRI. I agree that `nptyping` types that are equal should be identical.
