### ISSUE TITLE
Skipping analyzing 'nptyping': found module but no type hints or library stubs

### ISSUE THREAD

**Issue by johanvergeer** [ramonhagenaars/nptyping#32]
We just started to use MyPy, and one of the packages that showed up with `found module but no type hints or library stubs` was nptyping.

This feels really awkward since this package is meant to provide typing for numpy, but I'm probably missing something.

Can anyone tell me what I can do to solve this?

**Comment by ramonhagenaars** [comment]
Another issue has been opened for this. Please refer to #34.
