### ISSUE TITLE
Number is not Number

### ISSUE THREAD

**Issue by baterflyrity** [ramonhagenaars/nptyping#36]
Just simple example:

    In[1]:  isinstance(np.array([1.0, -2]),NDArray[Number])
    Out[2]: False
    In[3]:  isinstance(np.array([1.0, -2]),NDArray[float])
    Out[4]: True

Why does float is not considered to be a Number or Real? It's definitely a bug. 

See also python/mypy#3186

Guess this is not so hard to fix when nptyping uses runtime checks. Also guess I supposed to use libraries' Number. But is it as full featured as built-in?

**Comment by ramonhagenaars** [comment]
On my machine, I get:

```python
>>> from nptyping import NDArray, Number
>>> import numpy as np
>>> isinstance(np.array([1.0, -2]), NDArray[Number])
True
```

**Comment by baterflyrity** [comment]
> On my machine, I get:
> 
> ```python
> >>> from nptyping import NDArray, Number
> >>> import numpy as np
> >>> isinstance(np.array([1.0, -2]), NDArray[Number])
> True
> ```

Yes, but only in case Number is imported from nptyping but standard library. So.. in some cases array is not valid when it actually is.

**Comment by ramonhagenaars** [comment]
I have tried to reproduce the problem, but it seems to work with Python's builtin `Number` as well. This issue may have been fixed as some side effect of another fix. Anyway, I'm closing this now.

**Comment by baterflyrity** [comment]
Consider basic lib has fixed this issue.
