### ISSUE TITLE
typish 1.9.2 breaks isinstance(a, NDArray[...])

### ISSUE THREAD

**Issue by friggog** [ramonhagenaars/nptyping#46]
Recent update of [typish to 1.9.2](https://github.com/ramonhagenaars/typish/releases/tag/v1.9.2) has broken `isinstance(a, NDArray[(Any, 3), Float])` - now always returns False. Mypy checks seem to succeed still, downgrading typish to 1.9.1 resolves the issue

**Comment by TinDang97** [comment]
Up. Me too.
