### ISSUE TITLE
can't import after upgrading to 0.3.0

### ISSUE THREAD

**Issue by sashaostr** [ramonhagenaars/nptyping#5]
after upgrading to 0.3.0 getting 

> ModuleNotFoundError: No module named 'nptyping'

the module appears when  ``` freeze | grep nptyping ```
> nptyping==0.3.0

**Comment by ramonhagenaars** [comment]
Thank you @sashaostr for opening this issue.

I seem to have broken the ``setup.py`` which was not detectable by the tests. It has been fixed in ``0.3.1`` which I just released. You should be able to ``pip install`` it any moment.

**Comment by sashaostr** [comment]
Thanks for fast fix @ramonhagenaars and for the lib! Closing..
