### ISSUE TITLE
"setup.py" accidentally installs tests

### ISSUE THREAD

**Issue by leycec** [ramonhagenaars/nptyping#51]
See also ramonhagenaars/typish#28, which documents this issue in full. Sadly, both codebases suffer the same fate. Happily, the fix is trivial:

```
    # This line...
    packages=find_packages(exclude=('tests', 'test_resources')),

    # ...should really look like this instead.
    packages=find_packages(exclude=('tests', 'tests.*', 'test_resources', 'test_resources.*')),
```

**Comment by ramonhagenaars** [comment]
Again, thank you for your issue! Patch incoming!

**Comment by leycec** [comment]
You're most welcome. Thanks for being so prompt, cordial, and informative, Ramon. :heart: 

Oh, and you're probably already aware, but [NumPy ≥ 1.20.0 has begun providing official type-hinting support via the new `numpy.typing` subpackage and, in particular, the new `numpy.typing.NDArray` type-hinting factory](https://numpy.org/devdocs/reference/typing.html#numpy.typing.mypy_plugin.NDArray). It'd be *awesome* if `nptyping` could somehow unify its efforts with NumPy's, which would also go a long way to [resolving your lingering incompatibility with static analysis checkers (e.g., mypy, PyCharm)](https://github.com/ramonhagenaars/nptyping/issues/34).

`nptyping` still rocks, of course. Keep up all the great type hinting!
