### ISSUE TITLE
Add a test for setup.py

### ISSUE THREAD

**Issue by ramonhagenaars** [ramonhagenaars/nptyping#6]
The ``setup.py`` is not currently covered by any test. A test should be added that:

1. builds a wheel;
2. installs this wheel in a virtual environment;
3. imports nptyping and does some basic stuff.

**Comment by EricCousineau-TRI** [comment]
Peanut gallery: I think you've done this with your CI?
https://github.com/ramonhagenaars/nptyping/blob/c813f6d235ed9eab0070bc51340ae0c58750f73e/.travis.yml#L14-L17

**Comment by ramonhagenaars** [comment]
That tests the dependencies, but not the wheel building. This issue may be a bit far fetched though.
