### ISSUE TITLE
Is one-more-abstract version of type-enforcing available?

### ISSUE THREAD

**Issue by syyunn** [ramonhagenaars/nptyping#9]
I'd like to enforce the type such as Array[float, n, n] where n is arbitrary int, thus it allows any ndarray that has same shape on 1st and 2nd dimension. 

Is this feature currently available with the nptyping?

**Comment by ramonhagenaars** [comment]
Hi Syyunn. Unfortunately no, this feature is currently not available. Or at least, the instance check won't cover this.

When considering your question, at first I thought towards something with `TypeVar`:
```python
from typing import TypeVar
from nptyping import Array


T = TypeVar('T')
Array[float, T, T]
```
However, the `TypeVar` only fixes the type, not the value. In other words, `T` and `T` are ensured to be of the same type here, not of the same value.

A better approach might be to subclass `Array` and define your own instance-check. Something so you could do this:

```python
SquareArray[float, 5]  # Where 5 is the size of both dimenions.
```

**Comment by syyunn** [comment]
The second paragraph solution is a good idea and I never know your library support SquareArray. Thanks for your contribution and I really love to use your nptyping. Thanks!
