### ISSUE TITLE
PyCharm reports syntax error when using Shape['*'] in variable declarations

### ISSUE THREAD

**Issue by nikolajsheller** [ramonhagenaars/nptyping#90]
The following will run correctly:
```
    a: NDArray[Shape['*']] = np.array([1, 2, 3])
    isinstance(a, NDArray[Shape['*'], Int])
```
But causes PyCharm to issue the syntax error:
> Statement expected, found Py:MULT

**Comment by ramonhagenaars** [comment]
This is unfortunate behavior by PyCharm that cannot be solved by `nptptying`. I am about to release a patch that would allow you to use extra quotes as follows:
```python
Shape['"*"']
```
This will appease PyCharm. Though I agree that it looks less attractive, at least it offers you a choice. As I state in [the FAQ](https://github.com/ramonhagenaars/nptyping/blob/Release/2.3.1/USERDOCS.md#faq) of the release to come, there is only this option, or the option of accepting the PyCharm complaints... alas.

**Comment by nikolajsheller** [comment]
Thank you for your reply @ramonhagenaars, I think I will go with the extra quote solution.
It is very distracting to me when PyCharm complains.

Thank you for your work

**Comment by ramonhagenaars** [comment]
There is one other option I forgot to mention. You can also replace `Shape` by `typing.Literal`, this will silence the PyCharm complaints as well. 

If you use an alias, it doesn't look so bad:
```python
from typing import Literal as Shape

s: Shape["*"]  # PyCharm is still happy.
```
