### ISSUE TITLE
How to get better __repr__ / autogenerated docstring for functions with type hints?

### ISSUE THREAD

**Issue by nikolas-claussen** [ramonhagenaars/nptyping#99]
Hi there,

Would it be possible to get the type hints in a function definition automatically integrated into the function's docstring and/or string representation? Using the example from the github page, the function
`def plan_route(locations: NDArray[Shape["[from, to], [x, y]"], Float]) -> NDArray[Shape["* stops, [x, y]"], Float]:    
    pass
`
currently has the following `help` string:
`plan_route(locations: nptyping.base_meta_classes.NDArray) -> nptyping.base_meta_classes.NDArray`
which is not very helpful. The desired behavior would be something like:
`plan_route(locations: NDArray[Shape["[from, to], [x, y]"], Float]) -> NDArray[Shape["* stops, [x, y]"], Float]`

Or is this already supported?

**Comment by ramonhagenaars** [comment]
Hi @nikolas-claussen ,

I looked into this and it turns out that the help text does not use `__str__` or `__repr__`. There is no trivial way to control what is shown in the help text.

However, with some ~dirty hacks~ special tricks, I managed to make the help text more helpful. Look for it in release `2.5.0`.

**Comment by nikolas-claussen** [comment]
Thanks a lot!

**Comment by ramonhagenaars** [comment]
With [v2.5.0](https://github.com/ramonhagenaars/nptyping/releases/tag/v2.5.0) this issue should be resolved. Please let me know if you encounter any problems still.

**Comment by nikolas-claussen** [comment]
Hello Ramon,

Thank you so much! Works exactly as I hoped now.

Nikolas
